### PR TITLE
Convert the scamandrill library to use play-ws

### PR DESCRIPTION
**Pull request by joelsonoda**
Scamandrill has been updated to use play-ws with play-json to communicate
with mandrill. This allows us to integrate more cleanly with playframework
applications.

Notable changes are:
  - Created mock test cases for every example listed in the mandrill API docs.
  - Modify some of the objects to better reflect the API description on the docs.
  - API Key is specified on a per-client basis rather than globally or per request.
  - Added some implicits to assist in the construction of mandrill requests.

### CODE REVIEW

**Comment by joelsonoda** [comment]
Can you set the environment variable SCAMANDRILL_TEST_MESSAGE_ID to the ID of one of the very recent test emails (should be subject "subject test" to "test@example.com"). I cannot seem to find info about the email with the ID specified in the MandrillTestUtils.

Thanks

**Comment by graingert** [comment]
Will do

**Comment by graingert** [comment]
@joelsonoda I can't find that email ID, so I invited you to manage the Mailchimp (and therefore Mandrill add-on) account.

**Comment by joelsonoda** [comment]
I think maybe there's a problem with the account that prevents the email from sending, so I can't find it. I looked at the mailchimp account (still doesn't authorize me for mandrill), and it was giving warnings about being in violation of TOS, so I am wondering if that prohibits from sending in mandrill.

In the meantime, I set travis to use a test key from my personal account.

I changed the tests to use the ID of one of the messages returned in a search for performing info and content tests (since [mandrill only keeps info on email for 30 days ](https://mandrill.zendesk.com/hc/en-us/articles/205583157-How-long-does-Mandrill-keep-data-about-my-emails-)). If it doesn't find one of the test emails in history, it will send a test email so that the next time it runs it should succeed.

**Comment by graingert** [comment]
Your personal account, do you use it to send real emails?

**Comment by joelsonoda** [comment]
No, the only active keys are test keys (I created the account only for
testing mandrill stuff).

**Comment by graingert** [comment]
@joelsonoda ok great :D clean up the commits and tell me when this is ready to land

**Comment by graingert** [comment]
@joelsonoda it's probably a good idea to update the docs while you're at it ;)

**Comment by joelsonoda** [comment]
@graingert Travis pending, but the commits are cleaned up.

**Comment by joelsonoda** [comment]
@graingert Do we want to stick with Jekyll pages for the docs, or should we use Readme.md?

I'm thinking maybe we merge this in and then do seperate PRs for the docs and other things that would be nice to clean up before 3.0 like 
 - Attachments changed to Bytestring source rather than array
 - Date parameters changed to "date" rather than string
 - More MSendMsg parameters should be optional so that they can default to the account's default sending configuration
 - GUICE module for providing a Scamandrill to play applications

What do you think?

**Comment by graingert** [comment]
Ok, that makes sense:

I'd like to see all these:

 - Attachments changed to Bytestring source rather than array
 - Date parameters changed to "date" rather than string (as long as it's polymorphic on types, String or Date allowed)
 - More MSendMsg parameters should be optional so that they can default to the account's default sending configuration
 - GUICE module for providing a Scamandrill to play applications

**Pull request merged**
