### PR TITLE
Convert the scamandrill library to use play-ws

### PR DESCRIPTION
**Pull request by joelsonoda**
Scamandrill has been updated to use play-ws with play-json to communicate
with mandrill. This allows us to integrate more cleanly with playframework
applications.

Notable changes are:
  - Created mock test cases for every example listed in the mandrill API docs.
  - Modify some of the object to better reflect the API description on the docs.
  - API Key is specified on a per-client basis rather than globally or per request.
  - Added some implicits to assist in the construction of mandrill requests.

### CODE REVIEW

**Comment by joelsonoda** [comment]
It wouldn't let me reopen the last pr because of the force

**Comment by graingert** [comment]
Hmm apparently so. Is it possible to expand the version range for other
play releases?

**Comment by joelsonoda** [comment]
We would probably need to have multiple versions of the project to support multiple versions of the playframework. The models are fine and could be shared between projects as are the tests, but the client implementation would need to be different for a < 2.5 version of play-ws.

**Comment by joelsonoda** [comment]
Also, for the tests, I started using an environment variable SCAMANDRILL_DEFAULT_SENDER for setting the sender value in the tests so that I could run them on my personal domain mandrill account for testing purposes (defaults to scamandrill@test.com like before).
Those actual api calls all work for me, but I can't verify that they work with the key that travis is using. I think that if they were working before, they should still work.

**Comment by joelsonoda** [comment]
Also, if we were to break the modules/tests out of the project, it would be possible for someone to use a different web client (such as akka-http or even just apache http-client)

**Comment by joelsonoda** [comment]
FYI: I was able to use the scamandrill client with play 2.4 under the following conditions

For build.sbt
```
"io.github.scamandrill" %% "scamandrill" % "3.0.0-MT-RC1" excludeAll ExclusionRule(organization = "com.typesafe.play"),
"com.typesafe.play" %% "play-functional" % "2.5.3"
```

Also, you have to get the MandrillClient directly since Scamandrill() will reference classes that don't exist in 2.4 (or include, akka-stream, asynchttpclient, etc).
```
val mandrillClient = MandrillClient(ws, key=APIKey("mykey"))
```

Not sure what problems including a newer version of play-functional will produce.

**Comment by graingert** [comment]
@joelsonoda I've invited you to collaborate, this should give you access to the secret mandrill key.

**Comment by joelsonoda** [comment]
@graingert I'm not sure that I can see the travis configuration with access only to the scamandrill repository (I think travis uses github organizational membership to manage authorization).

**Comment by graingert** [comment]
You just need to create a pull request from a branch on scamandrill

**Pull request closed without merging**
