### PR TITLE
Add sbt-release and set the appropriate snapshot version for the 2.4.…

### PR DESCRIPTION
**Pull request by joelsonoda**
…x branch

### CODE REVIEW

**Comment by graingert** [comment]
both scamandrill and scamandrill_2.4 should have the same release version. They're just two different packages right?

**Comment by graingert** [comment]
maybe we should have these all in the same branch with:

```
.
├── scamandrill deps: scamandrill-core, play-ws % 2.5
├── scamandrill_2.4 deps: scamandrill-core, play-ws % 2.4
└── scamandrill-core
```

**Comment by joelsonoda** [comment]
I was thinking that there would be a 2.4.x version for play 2.4.x and a 2.5.x version for play 2.5.x similar to https://github.com/leanovate/play-mockws

**Comment by graingert** [comment]
ah that works, I thought we were on v3

**Pull request merged**
